version: '3.8'
services:
  app:
    build: .
    volumes:
      - ~/.m2:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: uisp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: mypass
    command: redis-server --requirepass mypass
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
